import Footer from "@/_components/shared/footer/Footer";
import Navbar from "@/_components/shared/navbar/Navbar";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Toaster position="top-center" />
      <Footer />
    </>
  );
}
